<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/code-language-labels-1.0.2/code-language-labels.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <title>What If? - Lecture Notes – Chapter 19: Time-Varying Treatments</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Chapter 19: Time-Varying Treatments</h1>

<div class="quarto-title-authors">
</div>

</section>
<section class="slide level2">

<!-- https://www.overleaf.com/learn/latex/Using_colors_in_LaTeX#Named_colors_provided_by_the_xcolor_package -->
<!-- \def\or{\theta}  -->
<!-- doesn't work for some reason -->
<p>Parts I and II of the book considered <strong>time-fixed</strong> treatments, whose value is determined once, at the start of follow-up. Many causal questions instead involve treatments whose value can change over time for the same individual: medical treatments, lifestyle habits, employment or marital status, occupational exposures. Part III extends the framework to these <strong>time-varying treatments</strong>, and this chapter introduces the terminology and concepts it needs.</p>
<aside class="notes">
<p>This chapter is based on <span class="citation" data-cites="hernan2020causal">Hernán and Robins (<a href="#/references" role="doc-biblioref" onclick="">2020, chap. 19</a>, pp.&nbsp;255-266)</span>.</p>
<p>The authors warn that this is one of the most technical chapters of the book, because simplifying the concepts further would cost too much rigor. The chapter defines causal effects for time-varying treatments, introduces treatment strategies and sequentially randomized experiments, states the identifiability conditions (sequential exchangeability, positivity, consistency), and uses SWIGs to show that some strategies can be identified when others cannot. How to estimate these effects is the subject of Chapters 20 and 21.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="the-causal-effect-of-time-varying-treatments-pp.-255-256" class="title-slide slide level1 center" data-number="1">
<h1><span class="header-section-number">1</span> 19.1 The Causal Effect of Time-Varying Treatments (pp.&nbsp;255-256)</h1>

</section>
<section class="slide level2">

<p>For a time-fixed treatment <span class="math inline">\(A\)</span> (1: treated, 0: untreated) given at time zero and an outcome <span class="math inline">\(Y\)</span> measured 60 months later, the average causal effect is the contrast <span class="math inline">\(\text{E}{\left[Y^{a=1}\right]} - \text{E}{\left[Y^{a=0}\right]}\)</span>. It need not mention <em>when</em> treatment occurs, because everybody’s treatment is determined at the same time.</p>
<p>A time-varying treatment needs time to be made explicit. Let <span class="math inline">\(A_k\)</span> be a dichotomous treatment that may change at each month <span class="math inline">\(k = 0, 1, \ldots, K\)</span>, with <span class="math inline">\(K = 59\)</span>.</p>
<div id="exm-hiv-tv" class="theorem example">
<p><span class="theorem-title"><strong>Example 1 (HIV and antiretroviral therapy)</strong></span> In a 5-year follow-up study of individuals infected with HIV, <span class="math inline">\(A_k = 1\)</span> if the individual receives antiretroviral therapy in month <span class="math inline">\(k\)</span> and <span class="math inline">\(A_k = 0\)</span> otherwise. Nobody was treated before the study started: <span class="math inline">\(A_{-1} = 0\)</span> for all individuals. The outcome <span class="math inline">\(Y\)</span> measures health status (higher is better) at the end of follow-up, time <span class="math inline">\(K + 1 = 60\)</span>.</p>
</div>
<aside class="notes">
<p>For simplicity the book provisionally assumes no losses to follow-up, no deaths, and perfectly measured variables. Time is indexed from zero (the first time of possible treatment is <span class="math inline">\(k = 0\)</span>) for compatibility with much of the published literature. Although the example has an outcome measured at a fixed time, the concepts carry over to time-varying and failure-time outcomes (see Technical Point 21.8 of the book).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div id="def-treatment-history" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1 (Treatment history)</strong></span> An overbar denotes history: <span class="math inline">\(\bar{A}_k = (A_0, A_1, \ldots, A_k)\)</span> is the treatment history from time 0 through time <span class="math inline">\(k\)</span>. The whole history through <span class="math inline">\(K\)</span>, <span class="math inline">\(\bar{A}_K\)</span>, is often written <span class="math inline">\(\bar{A}\)</span> without a subscript. Lower-case letters denote realizations: <span class="math inline">\(a_k\)</span> is a value of <span class="math inline">\(A_k\)</span>.</p>
</div>
<ul>
<li>An individual treated in every month has <span class="math inline">\(\bar{A} = (1, 1, \ldots, 1) = \bar{1}\)</span>.</li>
<li>An individual never treated has <span class="math inline">\(\bar{A} = (0, 0, \ldots, 0) = \bar{0}\)</span>.</li>
<li>Most individuals are treated during only part of follow-up, so their histories mix 1s and 0s and have no compact symbol.</li>
</ul>
</section>
<section class="slide level2">

<p>A contrast at a single time,</p>
<p><span class="math display">\[\text{E}{\left[Y^{a_k = 1}\right]} - \text{E}{\left[Y^{a_k = 0}\right]},\]</span></p>
<p>quantifies the effect of treatment at time <span class="math inline">\(k\)</span> only, not the effect of treatment at all times between 0 and 59. The average causal effect of a time-varying treatment must instead contrast mean counterfactual outcomes under two <strong>treatment strategies</strong> that specify treatment at every time from <span class="math inline">\(k = 0\)</span> to <span class="math inline">\(k = K\)</span>. Because there are many such strategies, the average causal effect of a time-varying treatment is <strong>not uniquely defined</strong>.</p>
</section></section>
<section>
<section id="treatment-strategies-pp.-256-257" class="title-slide slide level1 center" data-number="2">
<h1><span class="header-section-number">2</span> 19.2 Treatment Strategies (pp.&nbsp;256-257)</h1>

</section>
<section class="slide level2">

<div id="def-treatment-strategy" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 2 (Treatment strategy)</strong></span> A <strong>treatment strategy</strong> (also called a plan, policy, protocol, or regime) is a rule to assign treatment at each time <span class="math inline">\(k\)</span> of follow-up.</p>
</div>
<p>The strategies “always treat”, <span class="math inline">\(\bar{a} = \bar{1}\)</span>, and “never treat”, <span class="math inline">\(\bar{a} = \bar{0}\)</span>, define one average causal effect of <span class="math inline">\(\bar{A}\)</span> on <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[\text{E}{\left[Y^{\bar{a} = \bar{1}}\right]} - \text{E}{\left[Y^{\bar{a} = \bar{0}}\right]}.\]</span></p>
<aside class="notes">
<p>A general counterfactual theory for comparing treatment strategies was first articulated by Robins (1986, 1987, 1997a).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<p>Many other contrasts are possible. For example, <span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]} - \text{E}{\left[Y^{\bar{a}'}\right]}\)</span> could compare</p>
<ul>
<li>“treat every other month”, <span class="math inline">\(\bar{a} = (1, 0, 1, 0, \ldots)\)</span>, with</li>
<li>“treat in all months except the first”, <span class="math inline">\(\bar{a}' = (0, 1, 1, 1, \ldots)\)</span>.</li>
</ul>
<p>There are <span class="math inline">\(2^{K+1}\)</span> such static strategies, one for each combination of values <span class="math inline">\((a_0, a_1, \ldots, a_K)\)</span> of a dichotomous <span class="math inline">\(a_k\)</span>. These do not exhaust all strategies.</p>
<aside class="notes">
<p>The vector <span class="math inline">\((a_0, \ldots, a_K)\)</span> has <span class="math inline">\(K + 1\)</span> components, so there are <span class="math inline">\(2^{K+1}\)</span> such vectors. The book writes “at least <span class="math inline">\(2^K\)</span>”, a lower bound, and uses <span class="math inline">\(2^K\)</span> again when counting static strategies in Technical Point 19.3; these notes write <span class="math inline">\(2^{K+1}\)</span> throughout. The point is only that the number grows exponentially with the length of follow-up.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dynamic-strategies" class="slide level2">
<h2>Dynamic Strategies</h2>
<p>Let <span class="math inline">\(L_k\)</span> be the CD4 cell count (cells per microliter) measured at month <span class="math inline">\(k\)</span>, coded <span class="math inline">\(L_k = 1\)</span> when low (bad prognosis) and <span class="math inline">\(L_k = 0\)</span> otherwise; everybody starts with a high count, <span class="math inline">\(L_0 = 0\)</span>. Consider the strategy</p>
<blockquote>
<p>do not treat while <span class="math inline">\(L_k = 0\)</span>; start treatment when <span class="math inline">\(L_k = 1\)</span> and treat continuously after that.</p>
</blockquote>
<p>This strategy cannot be written as a fixed vector <span class="math inline">\(\bar{a} = (a_0, a_1, \ldots, a_K)\)</span> that gives every individual the same <span class="math inline">\(a_k\)</span> at time <span class="math inline">\(k\)</span>: at each time, who is treated depends on each individual’s evolving <span class="math inline">\(L_k\)</span>.</p>
<div id="def-dynamic-static" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 3 (Dynamic and static strategies)</strong></span> A <strong>dynamic treatment strategy</strong> is a rule in which the treatment <span class="math inline">\(a_k\)</span> at time <span class="math inline">\(k\)</span> depends on the evolution of an individual’s time-varying covariates <span class="math inline">\(\bar{L}_k\)</span>. Strategies <span class="math inline">\(\bar{a}\)</span> in which treatment does not depend on covariates are <strong>non-dynamic</strong> or <strong>static</strong> treatment strategies.</p>
</div>
</section>
<section class="slide level2">

<div title="Fine Point 19.1: Deterministic and Random Treatment Strategies">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Fine Point 19.1: Deterministic and Random Treatment Strategies</strong></p>
</div>
<div class="callout-content">
<ul>
<li><mark class="preview-element-added">A <strong>deterministic dynamic strategy</strong> is a rule <span class="math inline">\(g = [g_0(\bar{a}_{-1}, l_0), \ldots, g_K(\bar{a}_{K-1}, \bar{l}_K)]\)</span>, where <span class="math inline">\(g_k(\bar{a}_{k-1}, \bar{l}_k)\)</span> is the treatment assigned at <span class="math inline">\(k\)</span> to an individual with past history <span class="math inline">\((\bar{a}_{k-1}, \bar{l}_k)\)</span>. Example: <span class="math inline">\(g_k(\bar{a}_{k-1}, \bar{l}_k) = 1\)</span> if the CD4 count was low at or before <span class="math inline">\(k\)</span>, and 0 otherwise.</mark></li>
<li><mark class="preview-element-added">A <strong>deterministic static strategy</strong> is a rule <span class="math inline">\(g = [g_0(\bar{a}_{-1}), \ldots, g_K(\bar{a}_{K-1})]\)</span> that does not depend on <span class="math inline">\(\bar{l}_k\)</span>.</mark></li>
<li><mark class="preview-element-added"><strong>Random strategies</strong> assign a probability of treatment rather than a value. They can be static (“each month, independently, treat with probability 0.3”) or dynamic (“each month, independently, treat with probability 0.3 if the CD4 count is low; do not treat if it is high”).</mark></li>
</ul>
<p><mark class="preview-element-added">The strategy <span class="math inline">\(g\)</span> that maximizes <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> (when higher outcomes are better) is the <strong>optimal treatment strategy</strong>. For a drug, it will almost always be dynamic, since treatment must stop when toxicity develops. No random strategy can be preferred to the optimal deterministic one, but random strategies (randomized trials) remain scientifically necessary, because before the trial nobody knows which deterministic strategy is optimal. Unless noted otherwise, <span class="math inline">\(g\)</span> denotes a deterministic strategy.</mark></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>The book cites Young et al.&nbsp;(2014) for a taxonomy of treatment strategies.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="causal-effects-require-specified-strategies" class="slide level2">
<h2>Causal Effects Require Specified Strategies</h2>
<p>The average causal effect of a time-varying treatment is well defined only once the strategies being compared are specified, e.g.</p>
<ul>
<li><span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]} - \text{E}{\left[Y^{\bar{a}'}\right]}\)</span>: “always treat” versus “never treat”;</li>
<li><span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]} - \text{E}{\left[Y^{g}\right]}\)</span>: “always treat” versus “treat only after the CD4 count is low”.</li>
</ul>
<p><span class="math inline">\(g\)</span> denotes any strategy, static or dynamic; for a static strategy we sometimes write <span class="math inline">\(Y^{g = \bar{a}}\)</span> rather than <span class="math inline">\(Y^g\)</span> or <span class="math inline">\(Y^{\bar{a}}\)</span>. Even with only two options (treat or not) at each time, there are as many causal effects as there are pairs of strategies.</p>
<div title="Technical Point 19.1: On the Definition of Dynamic Strategies">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Technical Point 19.1: On the Definition of Dynamic Strategies</strong></p>
</div>
<div class="callout-content">
<p>Every dynamic strategy <span class="math inline">\(g\)</span> that depends on past treatment and covariates has a counterpart <span class="math inline">\(g'\)</span> that depends only on past covariates, defined recursively by <span class="math inline">\(g'_0(l_0) = g_0(\bar{a}_{-1} = 0, l_0)\)</span> and <span class="math inline">\(g'_k(\bar{l}_k) = g_k{\left(g'_{k-1}(\bar{l}_{k-1}), \bar{l}_k\right)}\)</span>. By consistency, an individual has the same treatment, covariate, and outcome history whether following <span class="math inline">\(g\)</span> or <span class="math inline">\(g'\)</span> from time zero, so <span class="math inline">\(Y^g = Y^{g'}\)</span>. In the observed data, an individual has followed <span class="math inline">\(g\)</span> through time <span class="math inline">\(t\)</span> if and only if they have followed <span class="math inline">\(g'\)</span> through <span class="math inline">\(t\)</span>. If treatment under <span class="math inline">\(g\)</span> already does not depend on past treatment, <span class="math inline">\(g\)</span> and <span class="math inline">\(g'\)</span> are identical.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>In the recursion, <span class="math inline">\(g'_{k-1}(\bar{l}_{k-1})\)</span> stands for the whole treatment history <span class="math inline">\(\bar{a}_{k-1}\)</span> that <span class="math inline">\(g'\)</span> would have produced through <span class="math inline">\(k-1\)</span> given <span class="math inline">\(\bar{l}_{k-1}\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="sequentially-randomized-experiments-pp.-257-259" class="title-slide slide level1 center" data-number="3">
<h1><span class="header-section-number">3</span> 19.3 Sequentially Randomized Experiments (pp.&nbsp;257-259)</h1>

</section>
<section class="slide level2">

<p>The book uses three causal diagrams with the first two times, <span class="math inline">\(k = 0\)</span> and <span class="math inline">\(k = 1\)</span>. In each, <span class="math inline">\(A_k\)</span> is treatment, <span class="math inline">\(L_k\)</span> the measured variables, <span class="math inline">\(U_k\)</span> unmeasured common causes of at least two variables, and <span class="math inline">\(Y\)</span> the outcome. In the HIV example, CD4 count <span class="math inline">\(L_k\)</span> is a consequence of unmeasured immune damage <span class="math inline">\(U_k\)</span>, which also lowers health status <span class="math inline">\(Y\)</span>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Figure</th>
<th style="text-align: center;">Arrows from <span class="math inline">\(\bar{L}_k\)</span> into <span class="math inline">\(A_k\)</span></th>
<th style="text-align: center;">Arrows from <span class="math inline">\(\bar{U}_k\)</span> into <span class="math inline">\(A_k\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19.1</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td>19.2</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td>19.3</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">yes</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>All participants are assumed to adhere to the assigned treatment. A causal graph must include all common causes of any two variables on it, which is why the <span class="math inline">\(U_k\)</span> appear even though they are not measured.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="figure-19.1-treatment-depends-only-on-past-treatment" class="slide level2">
<h2>Figure 19.1: Treatment Depends Only on Past Treatment</h2>
<p>Example: each month, treatment is assigned with probability 0.5 to those untreated the previous month (<span class="math inline">\(A_{k-1} = 0\)</span>) and with probability 1 to those treated the previous month (<span class="math inline">\(A_{k-1} = 1\)</span>).</p>
<ul>
<li>For static strategies, this is the generalization of <em>no confounding by measured or unmeasured variables</em>.</li>
<li>Then <span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]} = \text{E}{\left[Y \mid \bar{A} = \bar{a}\right]}\)</span>: the counterfactual mean under <span class="math inline">\(\bar{a}\)</span> is the mean among those who followed <span class="math inline">\(\bar{a}\)</span>.</li>
</ul>
<aside class="notes">
<p>This equality does <strong>not</strong> in general extend to dynamic strategies. Under a dynamic strategy <span class="math inline">\(g\)</span> that depends on <span class="math inline">\(L\)</span>, <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> equals the mean outcome among those who followed <span class="math inline">\(g\)</span> only if the probability of <span class="math inline">\(A_k = 1\)</span> is exactly 0.5 at every time <span class="math inline">\(k\)</span> at which treatment under <span class="math inline">\(g\)</span> depends on <span class="math inline">\(L_k\)</span>. Otherwise, identifying <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> requires g-methods applied to data on <span class="math inline">\(L\)</span>, <span class="math inline">\(A\)</span>, and <span class="math inline">\(Y\)</span>, under either Figure 19.1 or Figure 19.2.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="figure-19.2-treatment-also-depends-on-measured-covariates" class="slide level2">
<h2>Figure 19.2: Treatment Also Depends on Measured Covariates</h2>
<p>Example: each month, treatment is assigned with probability</p>
<ul>
<li>0.4 to untreated individuals with high CD4 count,</li>
<li>0.8 to untreated individuals with low CD4 count,</li>
<li>0.5 to previously treated individuals (<span class="math inline">\(A_{k-1} = 1\)</span>), whatever their CD4 count.</li>
</ul>
<p>There is confounding by measured, but not unmeasured, variables.</p>
<aside class="notes">
<p>The book labels these strata “high CD4 (<span class="math inline">\(A_{k-1} = 0, L_k = 1\)</span>)” and “low CD4 (<span class="math inline">\(A_{k-1} = 0, L_k = 0\)</span>)”, which reverses the coding of Section 19.2 (<span class="math inline">\(L_k = 1\)</span> means low CD4). We describe the strata by CD4 level only; under the Section 19.2 coding, high CD4 is <span class="math inline">\(L_k = 0\)</span> and low CD4 is <span class="math inline">\(L_k = 1\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div id="def-seq-randomized" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4 (Sequentially randomized experiment)</strong></span> An experiment in which treatment is randomly assigned to each individual at each time <span class="math inline">\(k\)</span> is a <strong>sequentially randomized experiment</strong>.</p>
</div>
<ul>
<li>Figures 19.1 and 19.2 can represent sequentially randomized experiments.</li>
<li>Figure 19.3 cannot: there, <span class="math inline">\(A_k\)</span> depends partly on unmeasured <span class="math inline">\(U\)</span>, which investigators cannot use to assign treatment.</li>
<li>A sequentially randomized experiment has no arrows from unmeasured prognostic factors <span class="math inline">\(U\)</span> into any <span class="math inline">\(A_k\)</span>, however many time points <span class="math inline">\(k = 0, 1, \ldots, K\)</span> there are.</li>
</ul>
</section>
<section id="observational-studies" class="slide level2">
<h2>Observational Studies</h2>
<p>Treatment decisions usually depend on prognostic factors, so observational studies are typically represented by Figure 19.2 or 19.3, not 19.1.</p>
<ul>
<li>If clinicians’ decisions at each month depend on <span class="math inline">\((\bar{A}_{k-1}, \bar{L}_k)\)</span> but on no unmeasured <span class="math inline">\(\bar{U}_k\)</span>, the study is represented by Figure 19.2. It then differs from a sequentially randomized experiment only in that the assignment probabilities are unknown (though estimable from the data).</li>
<li>The data cannot tell us whether Figure 19.2 or Figure 19.3 is correct. Figure 19.3 has unmeasured confounding.</li>
</ul>
<aside class="notes">
<p>Sequentially randomized experiments are rarely run in practice, but the concept clarifies the conditions needed for valid estimation of the effects of time-varying treatments, which the next section states formally.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="sequential-exchangeability-pp.-259-260" class="title-slide slide level1 center" data-number="4">
<h1><span class="header-section-number">4</span> 19.4 Sequential Exchangeability (pp.&nbsp;259-260)</h1>

</section>
<section class="slide level2">

<p>For a time-fixed treatment, valid inference typically requires conditional exchangeability <span class="math inline">\(Y^a \perp\!\!\!\perp A \mid L\)</span>, which holds in conditionally randomized experiments and in observational studies where treatment depends on measured <span class="math inline">\(L\)</span> and, given <span class="math inline">\(L\)</span>, on no unmeasured common cause of treatment and outcome.</p>
<p>For a time-varying treatment we need conditional exchangeability <strong>at each time</strong>, given the covariate history <span class="math inline">\(\bar{L}_k\)</span>. With two times, this is</p>
<p><span class="math display">\[Y^g \perp\!\!\!\perp A_0 \mid L_0
\quad\text{and}\quad
Y^g \perp\!\!\!\perp A_1 \mid A_0 = g(L_0), L_0, L_1.\]</span></p>
<aside class="notes">
<p>The book drops the word “conditional” and says simply <strong>sequential exchangeability</strong>.</p>
<p>For individuals whose treatment history <span class="math inline">\([A_0 = g(L_0), A_1 = g(A_0, L_0, L_1)]\)</span> is compatible with strategy <span class="math inline">\(g\)</span> through the end of follow-up, consistency gives <span class="math inline">\(Y^g = Y\)</span>, which also equals the counterfactual outcome under the static strategy <span class="math inline">\((a_0, a_1) = (A_0, A_1)\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div id="def-seq-exchangeability" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5 (Sequential exchangeability for <span class="math inline">\(Y^g\)</span>)</strong></span> <span class="math display">\[Y^g \perp\!\!\!\perp A_k \mid \bar{A}_{k-1} = g(\bar{A}_{k-2}, \bar{L}_{k-1}), \bar{L}_k
\quad \text{for all strategies } g \text{ and } k = 0, 1, \ldots, K.\]</span></p>
<p>That is, at each time <span class="math inline">\(k\)</span>, the treated and untreated are exchangeable for <span class="math inline">\(Y^g\)</span> given prior covariate history <span class="math inline">\(\bar{L}_k\)</span> and any observed treatment history compatible with <span class="math inline">\(g\)</span>.</p>
</div>
<ul>
<li>A sequentially randomized experiment, in which <span class="math inline">\(A_k\)</span> is randomized with probability depending only on <span class="math inline">\(\bar{L}_k\)</span> and <span class="math inline">\(\bar{A}_{k-1}\)</span>, implies sequential exchangeability for <span class="math inline">\(Y^g\)</span>.</li>
<li>More generally, it holds in any causal graph that, like Figure 19.2, has <strong>no arrows from unmeasured <span class="math inline">\(U\)</span> into treatment</strong>.</li>
<li>So under Figure 19.2, <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> is identified for <strong>all</strong> strategies <span class="math inline">\(g\)</span>; under Figure 19.3, for <strong>none</strong>. Under other diagrams, it may be identified for some strategies but not others.</li>
</ul>
<aside class="notes">
<p>“This form of sequential exchangeability” signals that there are others, some weaker (Section 19.5) and some stronger (Technical Point 19.3).</p>
<p>Whenever the book talks about identification, the identifying formula is the g-formula (Chapter 21). In rare cases, not relevant here, effects can be identified by formulas related to but different from the g-formula (e.g., the front door formula of Technical Point 7.3).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="unconditional-sequential-exchangeability" class="slide level2">
<h2>Unconditional Sequential Exchangeability</h2>
<p>Under Figure 19.1, <strong>sequential unconditional exchangeability</strong> holds for every static strategy <span class="math inline">\(\bar{a}\)</span>:</p>
<p><span class="math display">\[Y^{\bar{a}} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1} = \bar{a}_{k-1}, \qquad k = 0, 1, \ldots, K.\]</span></p>
<p>It implies that association is causation: <span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]} = \text{E}{\left[Y \mid \bar{A} = \bar{a}\right]}\)</span>.</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em> (Derivation for <span class="math inline">\(K = 1\)</span>). </span><span class="math display">\[\begin{align}
\text{E}{\left[Y^{a_0, a_1}\right]}
&amp;= \text{E}{\left[Y^{a_0, a_1} \mid A_0 = a_0\right]}
  &amp;&amp; \text{(exchangeability at } k = 0\text{; positivity: } \Pr[A_0 = a_0] &gt; 0\text{)} \\
&amp;= \text{E}{\left[Y^{a_0, a_1} \mid A_0 = a_0, A_1 = a_1\right]}
  &amp;&amp; \text{(exchangeability at } k = 1 \text{, given } A_0 = a_0\text{; positivity: } \Pr[A_1 = a_1 \mid A_0 = a_0] &gt; 0\text{)} \\
&amp;= \text{E}{\left[Y \mid A_0 = a_0, A_1 = a_1\right]}
  &amp;&amp; \text{(consistency: } Y^{a_0, a_1} = Y \text{ when } (A_0, A_1) = (a_0, a_1)\text{)}
\end{align}\]</span></p>
<p>The positivity conditions make each conditional expectation well defined: without them, no one in the data has the history <span class="math inline">\((a_0, a_1)\)</span> to condition on. With more time points, repeat the middle step once for each <span class="math inline">\(k\)</span>, each time requiring <span class="math inline">\(\Pr[A_k = a_k \mid \bar{A}_{k-1} = \bar{a}_{k-1}] &gt; 0\)</span>.</p>
</div>
</section>
<section id="a-diagram-with-partial-identification" class="slide level2">
<h2>A Diagram With Partial Identification</h2>
<p>Figure 19.4 includes an unmeasured <span class="math inline">\(W_0\)</span> that causes both <span class="math inline">\(A_0\)</span> and the measured CD4 count <span class="math inline">\(L_1\)</span>, e.g.&nbsp;an unrecorded scheduled clinic visit at time 0; <span class="math inline">\(U_1\)</span> is the true (unknown) CD4 count, which <span class="math inline">\(L_1\)</span> measures with error.</p>
<ul>
<li><span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]}\)</span> is still identified for every <strong>static</strong> strategy <span class="math inline">\(\bar{a}\)</span>.</li>
<li><span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> is <strong>not</strong> identified for any <strong>dynamic</strong> strategy <span class="math inline">\(g\)</span> whose assignment depends on <span class="math inline">\(L_1\)</span>.</li>
</ul>
<p>Section 19.5 uses SWIGs to show why.</p>
</section>
<section id="positivity-and-consistency" class="slide level2">
<h2>Positivity and Consistency</h2>
<p>Identification also needs sequential versions of positivity and consistency. Both are expected to hold in a sequentially randomized experiment. Under all three conditions, <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> is identified by methods that adjust appropriately for <span class="math inline">\((\bar{A}_{k-1}, \bar{L}_k)\)</span>: the g-formula (standardization), IP weighting, and g-estimation.</p>
<div title="Technical Point 19.2: Positivity and Consistency for Time-Varying Treatments">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Technical Point 19.2: Positivity and Consistency for Time-Varying Treatments</strong></p>
</div>
<div class="callout-content">
<p><strong>Sequential positivity:</strong></p>
<p><span class="math display">\[\text{if } f_{\bar{A}_{k-1}, \bar{L}_k}(\bar{a}_{k-1}, \bar{l}_k) \neq 0,
\text{ then } f_{A_k \mid \bar{A}_{k-1}, \bar{L}_k}(a_k \mid \bar{a}_{k-1}, \bar{l}_k) &gt; 0
\text{ for all } \bar{a}_k, \bar{l}_k.\]</span></p>
<p>It holds in a sequentially randomized experiment if the randomization probabilities are never 0 or 1, whatever the past history. For a particular strategy <span class="math inline">\(g\)</span>, it need hold only for treatment histories compatible with <span class="math inline">\(g\)</span>, i.e., <span class="math inline">\(a_k = g(\bar{a}_{k-1}, \bar{l}_k)\)</span> for each <span class="math inline">\(k\)</span>.</p>
<p><strong>Sequential consistency:</strong></p>
<p><span class="math display">\[Y^{\bar{a}} = Y^{\bar{a}^*} \text{ if } \bar{a}^* = \bar{a};
\quad Y^{\bar{a}} = Y \text{ if } \bar{A} = \bar{a};
\quad \bar{L}_k^{\bar{a}} = \bar{L}_k^{\bar{a}^*} \text{ if } \bar{a}^*_{k-1} = \bar{a}_{k-1};
\quad \bar{L}_k^{\bar{a}} = \bar{L}_k \text{ if } \bar{A}_{k-1} = \bar{a}_{k-1},\]</span></p>
<p>where <span class="math inline">\(\bar{L}_k^{\bar{a}}\)</span> is the counterfactual covariate history through <span class="math inline">\(k\)</span> under <span class="math inline">\(\bar{a}\)</span>. Weaker conditions suffice for identification (“if <span class="math inline">\(\bar{A} = \bar{a}\)</span> then <span class="math inline">\(Y^{\bar{a}} = Y\)</span>” for static strategies; “if <span class="math inline">\(A_k = g_k(\bar{A}_{k-1}, \bar{L}_k)\)</span> at each <span class="math inline">\(k\)</span> then <span class="math inline">\(Y^g = Y\)</span>” for dynamic ones), but the book always accepts the stronger sequential version. If “treat in month <span class="math inline">\(k\)</span>” and “do not treat in month <span class="math inline">\(k\)</span>” are sufficiently well defined at all <span class="math inline">\(k\)</span>, so are all static and dynamic strategies built from them.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="identifiability-under-some-but-not-all-treatment-strategies-pp.-261-264" class="title-slide slide level1 center" data-number="5">
<h1><span class="header-section-number">5</span> 19.5 Identifiability Under Some but Not All Treatment Strategies (pp.&nbsp;261-264)</h1>

</section>
<section class="slide level2">

<p>The backdoor criterion of Chapter 7 generalizes to time-varying treatments. For static strategies, a sufficient condition for identification is that, <strong>at each time <span class="math inline">\(k\)</span>, all backdoor paths into <span class="math inline">\(A_k\)</span> that do not go through any future treatment are blocked</strong>.</p>
<p>But this generalized criterion works on causal DAGs, which contain no counterfactual outcomes, so it does not show the connection to sequential exchangeability directly. SWIGs (Chapter 7) do, and are especially useful here.</p>
<aside class="notes">
<p>Pearl and Robins (1995) proposed a generalized backdoor criterion for static strategies; Robins (1997a) extended it to dynamic strategies.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-simplified-diagrams" class="slide level2">
<h2>Two Simplified Diagrams</h2>
<p>Figures 19.5 and 19.6 simplify Figures 19.2 and 19.4: they drop <span class="math inline">\(U_0\)</span>, <span class="math inline">\(L_0\)</span>, the arrow <span class="math inline">\(A_0 \to U_1\)</span>, and the arrow <span class="math inline">\(L_1 \to Y\)</span>. Both include, among others, the arrows</p>
<p><span class="math display">\[A_0 \to L_1, \quad A_0 \to A_1, \quad L_1 \to A_1, \quad U_1 \to L_1, \quad U_1 \to Y, \quad A_1 \to Y.\]</span></p>
<p>They differ in one respect:</p>
<ul>
<li><strong>Figure 19.5</strong>: no shared cause of <span class="math inline">\(A_0\)</span> and <span class="math inline">\(L_1\)</span>.</li>
<li><strong>Figure 19.6</strong>: an unmeasured <span class="math inline">\(W_0\)</span> with <span class="math inline">\(W_0 \to A_0\)</span> and <span class="math inline">\(W_0 \to L_1\)</span>.</li>
</ul>
<aside class="notes">
<p>The arrows listed are those the book’s text relies on (the backdoor paths <span class="math inline">\(A_1 \leftarrow L_1 \leftarrow U_1 \to Y\)</span> and <span class="math inline">\(A_1 \leftarrow A_0 \to L_1 \leftarrow U_1 \to Y\)</span> of Section 19.6, and the SWIG paths of this section); consult the book’s figures for the complete diagrams.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="building-the-swig-for-a-static-strategy" class="slide level2 scrollable">
<h2>Building the SWIG for a Static Strategy</h2>
<p>Figure 19.7 is the SWIG for Figure 19.5 under the static strategy <span class="math inline">\((a_0, a_1)\)</span>, e.g.&nbsp;“always treat” <span class="math inline">\((1, 1)\)</span> or “never treat” <span class="math inline">\((0, 0)\)</span>:</p>
<ol type="1">
<li>Split each treatment node. The right half is the value set by the intervention (<span class="math inline">\(a_0\)</span>, <span class="math inline">\(a_1\)</span>); the left half is the value that would be observed after intervening on all <em>earlier</em> treatments: <span class="math inline">\(A_0\)</span> itself, and <span class="math inline">\(A_1^{a_0}\)</span> for time 1.</li>
<li>Arrows into a treatment point into its left half; arrows out of a treatment leave from its right half.</li>
<li>Replace the outcome and covariates by counterfactuals: <span class="math inline">\(Y^{a_0, a_1}\)</span> and <span class="math inline">\(L_1^{a_0}\)</span>.</li>
</ol>
<p><span class="math inline">\(L_1\)</span> is written <span class="math inline">\(L_1^{a_0}\)</span>, not <span class="math inline">\(L_1^{a_0, a_1}\)</span>, because a later intervention on <span class="math inline">\(A_1\)</span> cannot affect the earlier <span class="math inline">\(L_1\)</span>. Unlike the DAG, the SWIG contains the counterfactual outcome, so exchangeability can be checked by d-separation.</p>
</section>
<section id="static-sequential-exchangeability" class="slide level2 scrollable">
<h2>Static Sequential Exchangeability</h2>
<p>In Figure 19.7, d-separation gives, for every <span class="math inline">\((a_0, a_1)\)</span>,</p>
<p><span class="math display">\[Y^{a_0, a_1} \perp\!\!\!\perp A_0
\quad\text{and}\quad
Y^{a_0, a_1} \perp\!\!\!\perp A_1^{a_0} \mid A_0, L_1^{a_0}.\]</span></p>
<p>The path <span class="math inline">\(A_1^{a_0} \leftarrow a_0 \to L_1^{a_0} \leftarrow U_1 \to Y^{a_0, a_1}\)</span> looks open, but it is blocked: <span class="math inline">\(a_0\)</span> is a constant in the counterfactual world, and constants are always implicitly conditioned on (Fine Point 19.2).</p>
<div class="proof">
<p><span class="proof-title"><em>Proof</em> (From the SWIG statement to an observed-data statement). </span></p>
<ol type="1">
<li><span class="math inline">\(Y^{a_0, a_1} \perp\!\!\!\perp A_1^{a_0} \mid A_0, L_1^{a_0}\)</span> implies, in particular, <span class="math inline">\(Y^{a_0, a_1} \perp\!\!\!\perp A_1^{a_0} \mid A_0 = a_0, L_1^{a_0}\)</span> (restrict to those who received <span class="math inline">\(A_0 = a_0\)</span>).</li>
<li>Among those with <span class="math inline">\(A_0 = a_0\)</span>, consistency gives <span class="math inline">\(L_1^{a_0} = L_1\)</span> and <span class="math inline">\(A_1^{a_0} = A_1\)</span>.</li>
<li>Substituting: <span class="math inline">\(Y^{a_0, a_1} \perp\!\!\!\perp A_1 \mid A_0 = a_0, L_1\)</span>.</li>
</ol>
</div>
</section>
<section class="slide level2">

<div id="def-static-seq-exchangeability" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6 (Static sequential exchangeability)</strong></span> <span class="math display">\[Y^{\bar{a}} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1} = \bar{a}_{k-1}, \bar{L}_k
\quad \text{for } k = 0, 1, \ldots, K.\]</span></p>
</div>
<ul>
<li>It is <strong>weaker</strong> than sequential exchangeability for <span class="math inline">\(Y^g\)</span> (<a href="#/def-seq-exchangeability" class="quarto-xref">Definition&nbsp;5</a>): it concerns only counterfactual outcomes indexed by static strategies <span class="math inline">\(g = \bar{a}\)</span>.</li>
<li>It suffices to identify <span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]}\)</span> for every static strategy.</li>
<li>It holds in Figure 19.6 too (check d-separation on its SWIG, Figure 19.8), so under Figure 19.6 every static strategy is identified.</li>
</ul>
<aside class="notes">
<p>Two variations on Figure 19.5:</p>
<ul>
<li>Without the arrow <span class="math inline">\(L_1 \to A_1\)</span>, the SWIG would lack <span class="math inline">\(L_1^{a_0} \to A_1^{a_0}\)</span>, so sequential <em>unconditional</em> exchangeability would hold and every static strategy could be identified without data on <span class="math inline">\(L_1\)</span>.</li>
<li>With an added arrow <span class="math inline">\(U_1 \to A_1\)</span>, the SWIG would have <span class="math inline">\(U_1 \to A_1^{a_0}\)</span>, no form of sequential exchangeability would hold, and no strategy would be identified.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div title="Technical Point 19.3: The Many Forms of Sequential Exchangeability">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Technical Point 19.3: The Many Forms of Sequential Exchangeability</strong></p>
</div>
<div class="callout-content">
<p>For a sequentially randomized experiment with times <span class="math inline">\(k = 0, 1, \ldots, K\)</span> (a longer version of Figure 19.7), the SWIG gives</p>
<p><span class="math display">\[{\left(Y^{\bar{a}}, \underline{L}_{k+1}^{\bar{a}}\right)} \perp\!\!\!\perp A_k^{\bar{a}_{k-1}}
\mid \bar{A}_{k-1}^{\bar{a}_{k-2}}, \bar{L}_k^{\bar{a}_{k-1}},\]</span></p>
<p>where <span class="math inline">\(\underline{L}_{k+1}^{\bar{a}}\)</span> is the counterfactual covariate history from <span class="math inline">\(k + 1\)</span> to the end of follow-up. Restricting to <span class="math inline">\(\bar{A}_{k-1}^{\bar{a}_{k-2}} = \bar{a}_{k-1}\)</span> and applying consistency gives</p>
<p><span class="math display">\[{\left(Y^{\bar{a}}, \underline{L}_{k+1}^{\bar{a}}\right)} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1} = \bar{a}_{k-1}, \bar{L}_k.\]</span></p>
<p>When this holds for all <span class="math inline">\(\bar{a}\)</span>, it is called <strong>sequential exchangeability</strong>. Although it mentions only static strategies, it is equivalent to</p>
<p><span class="math display">\[{\left(Y^{g}, \underline{L}_{k+1}^{g}\right)} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1} = g(\bar{A}_{k-2}, \bar{L}_{k-1}), \bar{L}_k
\quad \text{for all } g,\]</span></p>
<p>and so, with positivity, it identifies the outcome and covariate distributions under every static and dynamic strategy (Robins 1986). This rests on the <em>joint</em> independence of <span class="math inline">\((Y^{\bar{a}}, \underline{L}_{k+1}^{\bar{a}})\)</span> and <span class="math inline">\(A_k\)</span>; for dynamic strategies, the two <em>separate</em> independences of <span class="math inline">\(Y^{\bar{a}}\)</span> and of <span class="math inline">\(\underline{L}_{k+1}^{\bar{a}}\)</span> from <span class="math inline">\(A_k\)</span> do not suffice.</p>
<p>A sequentially randomized trial implies still stronger conditions, which cannot be read from SWIGs and are not needed for identification, e.g.</p>
<ul>
<li><span class="math inline">\({\left\{{\left(Y^{\bar{a}}, \underline{L}_{k+1}^{\bar{a}}\right)}; \text{all } \bar{a}\right\}} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1}, \bar{L}_k\)</span>;</li>
<li><strong>full sequential exchangeability</strong>: <span class="math inline">\({\left(Y^{\bar{\mathcal{A}}}, \bar{L}^{\bar{\mathcal{A}}}\right)} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1}, \bar{L}_k\)</span>, where <span class="math inline">\(\bar{\mathcal{A}}\)</span> is the set of all <span class="math inline">\(2^{K+1}\)</span> static strategies, and <span class="math inline">\(Y^{\bar{\mathcal{A}}}\)</span>, <span class="math inline">\(\bar{L}^{\bar{\mathcal{A}}}\)</span> the corresponding sets of counterfactuals (by analogy with Technical Point 2.1).</li>
</ul>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>We write <span class="math inline">\(\underline{L}_{k+1}\)</span> (an underbar for “from <span class="math inline">\(k + 1\)</span> onward”) and <span class="math inline">\(\bar{\mathcal{A}}\)</span> for the set of static strategies; the book’s typography for these symbols differs slightly. In the dynamic version we write the conditioning history as <span class="math inline">\(g(\bar{A}_{k-2}, \bar{L}_{k-1})\)</span>, matching <a href="#/def-seq-exchangeability" class="quarto-xref">Definition&nbsp;5</a>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="swigs-for-dynamic-strategies" class="slide level2">
<h2>SWIGs for Dynamic Strategies</h2>
<p>Figure 19.9 represents Figure 19.5 under a dynamic strategy <span class="math inline">\(g = [g_0, g_1(L_1)]\)</span>: <span class="math inline">\(A_0\)</span> is set to a fixed <span class="math inline">\(g_0\)</span>, and <span class="math inline">\(A_1\)</span> to <span class="math inline">\(g_1(L_1^g)\)</span>, which depends on the <span class="math inline">\(L_1^g\)</span> observed after setting <span class="math inline">\(A_0 = g_0\)</span>.</p>
<div id="exm-dynamic-swig" class="theorem example">
<p><span class="theorem-title"><strong>Example 2 (“Treat at time 1 only if CD4 is low”)</strong></span> Strategy: do not treat at time 0; at time 1 treat only if the CD4 count is low (<span class="math inline">\(L_1^g = 1\)</span>). So <span class="math inline">\(g_0 = 0\)</span> for everybody, <span class="math inline">\(g_1(L_1^g) = 1\)</span> when <span class="math inline">\(L_1^g = 1\)</span>, and <span class="math inline">\(g_1(L_1^g) = 0\)</span> when <span class="math inline">\(L_1^g = 0\)</span>.</p>
</div>
<ul>
<li>The SWIG gains an arrow <span class="math inline">\(L_1^g \to g_1(L_1^g)\)</span> that is not in the original DAG; it exists only in the counterfactual world of this strategy. It is drawn differently but treated like any other arrow for d-separation.</li>
<li>The outcome node is <span class="math inline">\(Y^g\)</span>.</li>
</ul>
</section>
<section id="figure-19.9-versus-figure-19.10" class="slide level2">
<h2>Figure 19.9 Versus Figure 19.10</h2>
<ul>
<li><strong>Figure 19.9</strong> (from Figure 19.5): d-separation gives <span class="math inline">\(Y^g \perp\!\!\!\perp A_0\)</span> and <span class="math inline">\(Y^g \perp\!\!\!\perp A_1^g \mid A_0 = g_0, L_1^g\)</span> for every <span class="math inline">\(g\)</span>. Sequential exchangeability for <span class="math inline">\(Y^g\)</span> holds: <strong>all strategies, static and dynamic, are identified</strong>.</li>
<li><strong>Figure 19.10</strong> (from Figure 19.6): <span class="math inline">\(Y^g \perp\!\!\!\perp A_0\)</span> fails, because of the open path <span class="math display">\[A_0 \leftarrow W_0 \to L_1^g \to g_1(L_1^g) \to Y^g.\]</span> Sequential exchangeability for <span class="math inline">\(Y^g\)</span> fails, and <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> is not identified for the dynamic strategy.</li>
</ul>
<aside class="notes">
<p>From the SWIG we read <span class="math inline">\(Y^g \perp\!\!\!\perp A_1^g \mid A_0, L_1^g\)</span>, which by consistency implies <span class="math inline">\(Y^g \perp\!\!\!\perp A_1 \mid A_0 = g_0, L_1\)</span>.</p>
<p>Another way to see the Figure 19.10 problem: the distribution of <span class="math inline">\(Y^g\)</span> depends on that of <span class="math inline">\(g_1(L_1^g)\)</span>, hence on that of <span class="math inline">\(L_1^g\)</span>, and the distribution of <span class="math inline">\(L_1^g\)</span> is not identified because of the path <span class="math inline">\(A_0 \leftarrow W_0 \to L_1^g\)</span>. Under a static strategy, no arrow from <span class="math inline">\(L_1^{a_0}\)</span> into the treatment node feeds <span class="math inline">\(Y\)</span>, which is why static strategies remain identified under Figure 19.6.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div title="Fine Point 19.2: Arrows From Intervention Nodes in SWIGs">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Fine Point 19.2: Arrows From Intervention Nodes in SWIGs</strong></p>
</div>
<div class="callout-content">
<p>SWIGs include arrows from intervention nodes such as <span class="math inline">\(a\)</span> into later variables, even though in a single intervention world <span class="math inline">\(a\)</span> is a constant that cannot affect anything.</p>
<ul>
<li>The arrows record which variables <span class="math inline">\(A\)</span> directly affects in the original DAG.</li>
<li>Without them, the SWIGs of Figure 7.14 and of Figure 7.14 plus an arrow <span class="math inline">\(A \to Y\)</span> would be identical, and we could not tell that the effect is identified (by the front door formula) in the first DAG but not the second.</li>
</ul>
<p>So when applying d-separation to a SWIG, <strong>every path through an intervention node is blocked</strong>, even though the node is not written in the conditioning event.</p>
<p>The same holds for deterministic strategies that depend on a baseline confounder <span class="math inline">\(L_0\)</span> (replace <span class="math inline">\(g_0\)</span> by <span class="math inline">\(g_0(L_0)\)</span> in Figure 19.9): given <span class="math inline">\(L_0\)</span>, <span class="math inline">\(g_0(L_0)\)</span> is a constant, so paths through it are blocked, and <span class="math inline">\(Y^g \perp\!\!\!\perp A_1^g \mid A_0, L_0, L_1^g\)</span> becomes, after setting <span class="math inline">\(A_0 = g(L_0)\)</span> and using consistency, <span class="math inline">\(Y^g \perp\!\!\!\perp A_1 \mid A_0 = g(L_0), L_0, L_1\)</span>.</p>
<p>For a <strong>random</strong> strategy that draws <span class="math inline">\(A_0^{+,g}\)</span> from a distribution that may depend on <span class="math inline">\(L_0\)</span>, <span class="math inline">\(A_0^{+,g}\)</span> appears on the SWIG and must be conditioned on explicitly. Richardson and Robins (2013) showed that <span class="math inline">\(Y^g \perp\!\!\!\perp A_1^g \mid A_0, A_0^{+,g}, L_0, L_1^g\)</span> is necessary for identification by the g-formula for such a strategy. They also treated strategies that depend on the <em>natural value of treatment</em> <span class="math inline">\(A_t^g\)</span> (Robins et al.&nbsp;2004), recently called “modified treatment policies” (Diaz et al.&nbsp;2021).</p>
</div>
</div>
</div>
</div>
</section>
<section id="one-last-example" class="slide level2">
<h2>One Last Example</h2>
<p>Figure 19.11 is Figure 19.6 plus an arrow <span class="math inline">\(L_1 \to Y\)</span> (Figure 19.12 is its SWIG under a static strategy). Here neither sequential exchangeability for <span class="math inline">\(Y^g\)</span> nor static sequential exchangeability for <span class="math inline">\(Y^{\bar{a}}\)</span> holds, so <strong>no</strong> strategy’s effect can be validly estimated.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Diagram</th>
<th style="text-align: center;">Static strategies</th>
<th style="text-align: center;">Dynamic strategies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Figure 19.5</td>
<td style="text-align: center;">identified</td>
<td style="text-align: center;">identified</td>
</tr>
<tr class="even">
<td>Figure 19.6</td>
<td style="text-align: center;">identified</td>
<td style="text-align: center;">not identified</td>
</tr>
<tr class="odd">
<td>Figure 19.11</td>
<td style="text-align: center;">not identified</td>
<td style="text-align: center;">not identified</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Why Figure 19.11 fails even for static strategies: in its SWIG, <span class="math inline">\(L_1^{a_0}\)</span> is now a cause of <span class="math inline">\(Y^{a_0, a_1}\)</span>, so the path <span class="math inline">\(A_0 \leftarrow W_0 \to L_1^{a_0} \to Y^{a_0, a_1}\)</span> is open and <span class="math inline">\(Y^{a_0, a_1} \perp\!\!\!\perp A_0\)</span> fails; conditioning on <span class="math inline">\(L_1\)</span> to block it is not allowed at time 0, because <span class="math inline">\(L_1\)</span> comes after <span class="math inline">\(A_0\)</span>. This explanation is ours; the book states only the conclusion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="time-varying-confounding-and-time-varying-confounders-pp.-265-266" class="title-slide slide level1 center" data-number="6">
<h1><span class="header-section-number">6</span> 19.6 Time-Varying Confounding and Time-Varying Confounders (pp.&nbsp;265-266)</h1>

</section>
<section class="slide level2">

<p>No form of sequential exchangeability is guaranteed in an observational study. Approximating it requires expert knowledge to decide which time-varying variables <span class="math inline">\(\bar{L}_k\)</span> to measure (in HIV: CD4 count, viral load, symptoms). Whether the measured covariates suffice can never be known with certainty, but causal diagrams such as Figures 19.1-19.4 organize our beliefs. These diagrams were drawn without selection (e.g., censoring) so as to focus on confounding.</p>
</section>
<section id="l_1-as-a-confounder-for-a_1" class="slide level2">
<h2><span class="math inline">\(L_1\)</span> as a Confounder for <span class="math inline">\(A_1\)</span></h2>
<p>In Figure 19.5, consider the effect of <span class="math inline">\(A_1\)</span> alone on <span class="math inline">\(Y\)</span>.</p>
<ul>
<li><span class="math inline">\(A_1\)</span> and <span class="math inline">\(Y\)</span> share the cause <span class="math inline">\(U\)</span>: the backdoor path <span class="math inline">\(A_1 \leftarrow L_1 \leftarrow U \to Y\)</span> is open, so there is confounding.</li>
<li><span class="math inline">\(U\)</span> is unmeasured, but conditioning on the measured <span class="math inline">\(L_1\)</span> blocks the path.</li>
<li>So if <span class="math inline">\(L_1\)</span> is measured, there is no unmeasured confounding for the effect of <span class="math inline">\(A_1\)</span>, and we call <span class="math inline">\(L_1\)</span> a <strong>confounder</strong> for that effect, even though the actual common cause is <span class="math inline">\(U\)</span> (see Section 7.3) and even though there is no arrow <span class="math inline">\(L_1 \to Y\)</span>.</li>
</ul>
<aside class="notes">
<p>Conditioning on <span class="math inline">\(L_1\)</span>, a collider, opens a second backdoor path, <span class="math inline">\(A_1 \leftarrow A_0 \to L_1 \leftarrow U \to Y\)</span>. That path can be blocked by also conditioning on prior treatment <span class="math inline">\(A_0\)</span>, if it is available.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div id="def-tv-confounders" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 7 (Time-varying confounders)</strong></span> Consider the long diagram over all times <span class="math inline">\(k = 0, 1, 2, \ldots\)</span>, in which each <span class="math inline">\(L_k\)</span> affects later treatments <span class="math inline">\(A_k, A_{k+1}, \ldots\)</span> and shares unmeasured causes <span class="math inline">\(U_k\)</span> with <span class="math inline">\(Y\)</span>. To estimate the effects of strategies defined by interventions on <span class="math inline">\(A_0, A_1, A_2, \ldots\)</span>, the covariate history <span class="math inline">\(\bar{L}_k\)</span>, together with <span class="math inline">\(\bar{A}_{k-1}\)</span>, is needed at each <span class="math inline">\(k\)</span> to block the backdoor paths between <span class="math inline">\(A_k\)</span> and <span class="math inline">\(Y\)</span>. The covariates in <span class="math inline">\(\bar{L}_k\)</span> are then called <strong>time-varying confounders</strong> for the effect of <span class="math inline">\(\bar{A}\)</span> on <span class="math inline">\(Y\)</span>.</p>
</div>
<ul>
<li>No unmeasured confounding for <span class="math inline">\(\bar{A}\)</span> requires that <span class="math inline">\(\bar{L}_k\)</span> be measured for everyone.</li>
<li>Time-varying confounders are sometimes called <strong>time-dependent confounders</strong>.</li>
<li>We cannot empirically tell Figure 19.2 (no unmeasured confounding) from Figure 19.3 (unmeasured confounding).</li>
<li>Even with all confounders measured and modeled correctly, most adjustment methods can give biased comparisons of strategies; Chapter 20 explains why g-methods are needed.</li>
</ul>
</section>
<section class="slide level2">

<div title="Fine Point 19.3: A Definition of Time-Varying Confounding">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Fine Point 19.3: A Definition of Time-Varying Confounding</strong></p>
</div>
<div class="callout-content">
<p>Assume no selection bias.</p>
<ul>
<li>There is <strong>confounding</strong> for effects involving <span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]}\)</span> if <span class="math inline">\(\text{E}{\left[Y^{\bar{a}}\right]} \neq \text{E}{\left[Y \mid \bar{A} = \bar{a}\right]}\)</span>.</li>
<li>The confounding is <strong>solely time-fixed</strong> (wholly due to baseline covariates) if <span class="math inline">\(\text{E}{\left[Y^{\bar{a}} \mid L_0\right]} = \text{E}{\left[Y \mid \bar{A} = \bar{a}, L_0\right]}\)</span>, as when the only arrows into <span class="math inline">\(A_1\)</span> in Figure 19.2 come from <span class="math inline">\(A_0\)</span> and <span class="math inline">\(L_0\)</span>.</li>
<li>If the identifiability conditions hold but <span class="math inline">\(\text{E}{\left[Y^{\bar{a}} \mid L_0\right]} \neq \text{E}{\left[Y \mid \bar{A} = \bar{a}, L_0\right]}\)</span>, there is <strong>time-varying confounding</strong>.</li>
<li>If the identifiability conditions fail, as in Figure 19.3, there is <strong>unmeasured confounding</strong>.</li>
</ul>
<p>A sufficient condition for no time-varying confounding is unconditional sequential exchangeability, <span class="math inline">\(Y^{\bar{a}} \perp\!\!\!\perp A_k \mid \bar{A}_{k-1} = \bar{a}_{k-1}\)</span>, as in Figure 19.1. That diagram can in fact be pruned to <span class="math inline">\(A_0\)</span>, <span class="math inline">\(A_1\)</span>, and <span class="math inline">\(Y\)</span>: <span class="math inline">\(L_1\)</span> is not a common cause of two nodes, so drop it; then <span class="math inline">\(L_0\)</span> and <span class="math inline">\(U_1\)</span> are no longer common causes, so drop them; then <span class="math inline">\(U_0\)</span> is not either.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Note what the chapter does <strong>not</strong> yet require: a time-varying confounder here is simply a covariate needed to block backdoor paths at some time <span class="math inline">\(k\)</span>. Whether that covariate is also <em>affected by earlier treatment</em> (treatment-confounder feedback) is the subject of Chapter 20, and it is that feedback that makes conventional adjustment fail.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-number="7">
<h1><span class="header-section-number">7</span> Summary</h1>

</section>
<section class="slide level2">

<ul>
<li>The average causal effect of a time-varying treatment is a contrast of <span class="math inline">\(\text{E}{\left[Y^g\right]}\)</span> under two <strong>treatment strategies</strong>; it is not uniquely defined until the strategies are specified.</li>
<li>Strategies are <strong>static</strong> (<span class="math inline">\(\bar{a}\)</span>, not depending on covariates) or <strong>dynamic</strong> (<span class="math inline">\(g\)</span>, depending on the evolving <span class="math inline">\(\bar{L}_k\)</span>), and deterministic or random.</li>
<li>In a <strong>sequentially randomized experiment</strong>, treatment at each <span class="math inline">\(k\)</span> is randomized given <span class="math inline">\((\bar{A}_{k-1}, \bar{L}_k)\)</span>; this implies <strong>sequential exchangeability</strong>.</li>
<li>Identification needs sequential exchangeability, sequential positivity, and consistency.</li>
<li><strong>Static sequential exchangeability</strong> is weaker and identifies only static strategies; SWIGs show when a diagram (e.g., Figure 19.6) supports static but not dynamic strategies.</li>
<li><strong>Time-varying confounders</strong> are covariates <span class="math inline">\(\bar{L}_k\)</span> needed at each time to block backdoor paths; Chapter 20 explains why conventional methods fail to adjust for them.</li>
</ul>
</section></section>
<section>
<section id="references" class="title-slide slide level1 center" data-number="8">
<h1><span class="header-section-number">8</span> References</h1>

</section>
<section class="slide level2 smaller scrollable" id="references">

<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-hernan2020causal" class="csl-entry" role="listitem">
Hernán, Miguel A, and James M Robins. 2020. <em>Causal Inference: What If</em>. Chapman &amp; Hall/CRC. <a href="https://miguelhernan.org/whatifbook">https://miguelhernan.org/whatifbook</a>.
</div>
</div>


<script>
(function () {
  "use strict";

  /**
   * CSS selector matching all Quarto theorem and proof div environments.
   *
   * Quarto adds the `.theorem` class to all theorem-type divs
   * (theorem, lemma, corollary, proposition, conjecture, definition,
   * example, exercise, algorithm), so `.theorem[id]` covers all of them.
   * Proof-type environments (.proof, .remark, .solution) are listed
   * separately because they do not carry the `.theorem` class.
   */
  var THEOREM_SELECTOR = [
    ".theorem[id]",
    ".proof[id]",
    ".remark[id]",
    ".solution[id]",
  ].join(", ");

  function getQuartoHeadingAnchorIcon() {
    var afterBodyScript = document.getElementById("quarto-html-after-body");
    if (!afterBodyScript) {
      return null;
    }

    var match = afterBodyScript.textContent.match(/const icon = ["']([^"']+)["']/);
    return match ? match[1] : null;
  }

  // Quarto chain-link glyph from Bootstrap Icons.
  var chainLinkIconFallback = "\ue9cb";
  var headingAnchorIcon = getQuartoHeadingAnchorIcon();
  var defaultAnchorIconFallback =
    headingAnchorIcon && headingAnchorIcon !== "#" ? headingAnchorIcon : chainLinkIconFallback;

  function getDefaultAnchorTemplate() {
    var defaultAnchor =
      document.querySelector(".anchored > a.anchorjs-link") ||
      document.querySelector("a.anchorjs-link[data-anchorjs-icon]");
    if (!defaultAnchor) {
      return null;
    }

    return {
      icon: defaultAnchor.getAttribute("data-anchorjs-icon") || defaultAnchor.textContent.trim(),
      hasDataIcon: defaultAnchor.hasAttribute("data-anchorjs-icon"),
      style: defaultAnchor.getAttribute("style")
    };
  }

  function normalizeAnchorIcon(icon) {
    if (!icon || icon === "#") {
      return defaultAnchorIconFallback;
    }

    return icon;
  }

  function createChainLinkSvgIcon() {
    var svgNs = "http://www.w3.org/2000/svg";
    var svg = document.createElementNS(svgNs, "svg");
    svg.setAttribute("viewBox", "0 0 16 16");
    svg.setAttribute("fill", "currentColor");
    svg.setAttribute("aria-hidden", "true");
    svg.setAttribute("focusable", "false");
    svg.setAttribute("class", "div-anchor-icon");

    // Bootstrap Icons chain-link icon (bi-link-45deg), paths for the two
    // chain links and the connecting segment.
    [
      "M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-2H11a4 4 0 0 1-4 3H4a4 4 0 0 1 0-8h2.354z",
      "M9.646 10.5H12a3 3 0 1 0 0-6H9a3 3 0 0 0-2.83 2H5a4 4 0 0 1 4-3h3a4 4 0 0 1 0 8H9.646z",
      "M5.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"
    ].forEach(function (pathData) {
      var path = document.createElementNS(svgNs, "path");
      path.setAttribute("d", pathData);
      svg.appendChild(path);
    });

    return svg;
  }

  function alignDivAnchorWithDefault(anchor, template) {
    if (!anchor) {
      return;
    }

    anchor.classList.remove("external");
    anchor.classList.add("no-external");

    var normalizedIcon = normalizeAnchorIcon(template && template.icon);
    if (normalizedIcon === chainLinkIconFallback) {
      anchor.removeAttribute("data-anchorjs-icon");
      anchor.textContent = "";
      anchor.appendChild(createChainLinkSvgIcon());
    } else if (template && template.hasDataIcon) {
      anchor.setAttribute("data-anchorjs-icon", normalizedIcon);
      anchor.textContent = normalizedIcon;
    } else {
      anchor.removeAttribute("data-anchorjs-icon");
      anchor.textContent = normalizedIcon;
    }

    if (template && template.style) {
      anchor.setAttribute("style", template.style);
    } else {
      anchor.removeAttribute("style");
    }
  }

  function alignDivAnchorsWithDefault() {
    var template = getDefaultAnchorTemplate();
    document.querySelectorAll("a.div-anchor").forEach(function (anchor) {
      alignDivAnchorWithDefault(anchor, template);
    });
  }

  function ensureDivAnchorStyles() {
    if (document.getElementById("div-anchor-styles")) {
      return;
    }

    var style = document.createElement("style");
    style.id = "div-anchor-styles";
    style.textContent = [
      ".div-anchor {",
      "  opacity: 0;",
      "  font-size: 0.875em;",
      "  font-weight: 400;",
      "  margin-left: 0.375em;",
      "  text-decoration: none;",
      "  color: inherit;",
      "  vertical-align: middle;",
      "  transition: opacity 0.2s ease;",
      "}",
      ".div-anchor:hover,",
      ".div-anchor:focus {",
      "  opacity: 1;",
      "  text-decoration: none;",
      "}",
      ".div-anchor-icon {",
      "  width: 0.875em;",
      "  height: 0.875em;",
      "  vertical-align: -0.125em;",
      "}",
      ":is(.theorem, .proof, .remark, .solution):hover .div-anchor,",
      ":is(.theorem, .proof, .remark, .solution):focus-within .div-anchor {",
      "  opacity: 1;",
      "}"
    ].join("\n");
    document.head.appendChild(style);
  }

  /**
   * Add anchor links to all theorem/proof divs with ids on the page.
   */
  function addDivAnchors() {
    ensureDivAnchorStyles();

    var divs = document.querySelectorAll(THEOREM_SELECTOR);
    divs.forEach(function (div) {
      var id = div.id;
      if (!id) {
        return;
      }

      // Skip if already processed.
      if (div.querySelector(".div-anchor")) {
        return;
      }

      var anchor = document.createElement("a");
      anchor.className = "div-anchor anchorjs-link";
      anchor.href = "#" + id;
      anchor.setAttribute("aria-label", "Permalink to this block");
      anchor.classList.add("no-external");

      // Find the theorem-title or proof-title span
      var titleSpan = div.querySelector(".theorem-title, .proof-title");

      if (titleSpan) {
        // Insert anchor immediately after the title span
        titleSpan.insertAdjacentElement("afterend", anchor);
      } else {
        // Fallback: prepend to the first paragraph
        var firstPara = div.querySelector("p");
        if (firstPara) {
          firstPara.insertAdjacentElement("afterbegin", anchor);
        }
      }
    });

    alignDivAnchorsWithDefault();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", addDivAnchors);
  } else {
    addDivAnchors();
  }

  window.addEventListener("load", alignDivAnchorsWithDefault);
})();
</script>

<script>
function getQuartoHeadingAnchorIcon() {
  const afterBodyScript = document.getElementById("quarto-html-after-body");
  if (!afterBodyScript) {
    return null;
  }

  const match = afterBodyScript.textContent.match(/const icon = ["']([^"']+)["']/);
  return match ? match[1] : null;
}

// Quarto chain-link glyph from Bootstrap Icons.
const chainLinkIconFallback = "\ue9cb";
const headingAnchorIcon = getQuartoHeadingAnchorIcon();
const defaultAnchorIconFallback =
  headingAnchorIcon && headingAnchorIcon !== "#" ? headingAnchorIcon : chainLinkIconFallback;

function getDefaultAnchorTemplate() {
  // Prefer Quarto heading anchors first so the visible chain-link icon is reused.
  const defaultAnchor =
    document.querySelector(".anchored > a.anchorjs-link") ||
    document.querySelector("a.anchorjs-link[data-anchorjs-icon]");
  if (!defaultAnchor) {
    return null;
  }

  return {
    // Detect icon value from the template anchor's attribute or text.
    icon: defaultAnchor.getAttribute("data-anchorjs-icon") || defaultAnchor.textContent.trim(),
    hasDataIcon: defaultAnchor.hasAttribute("data-anchorjs-icon"),
    style: defaultAnchor.getAttribute("style")
  };
}

function normalizeAnchorIcon(icon) {
  if (!icon || icon === "#") {
    return defaultAnchorIconFallback;
  }

  return icon;
}

function createChainLinkSvgIcon() {
  const svgNs = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(svgNs, "svg");
  svg.setAttribute("viewBox", "0 0 16 16");
  svg.setAttribute("fill", "currentColor");
  svg.setAttribute("aria-hidden", "true");
  svg.setAttribute("focusable", "false");
  svg.setAttribute("class", "equation-anchor-icon");

  [
    "M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-2H11a4 4 0 0 1-4 3H4a4 4 0 0 1 0-8h2.354z",
    "M9.646 10.5H12a3 3 0 1 0 0-6H9a3 3 0 0 0-2.83 2H5a4 4 0 0 1 4-3h3a4 4 0 0 1 0 8H9.646z",
    "M5.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"
  ].forEach(function (pathData) {
    const path = document.createElementNS(svgNs, "path");
    path.setAttribute("d", pathData);
    svg.appendChild(path);
  });

  return svg;
}

function alignEquationAnchorWithDefault(anchor, template) {
  if (!anchor) {
    return;
  }

  anchor.classList.remove("external");
  anchor.classList.add("no-external");

  const normalizedIcon = normalizeAnchorIcon(template && template.icon);
  if (normalizedIcon === chainLinkIconFallback) {
    anchor.removeAttribute("data-anchorjs-icon");
    anchor.textContent = "";
    anchor.appendChild(createChainLinkSvgIcon());
  } else if (template && template.hasDataIcon) {
    anchor.setAttribute("data-anchorjs-icon", normalizedIcon);
    anchor.textContent = normalizedIcon;
  } else {
    anchor.removeAttribute("data-anchorjs-icon");
    anchor.textContent = normalizedIcon;
  }

  if (template && template.style) {
    anchor.setAttribute("style", template.style);
  } else {
    anchor.removeAttribute("style");
  }
}

function alignEquationAnchorsWithDefault() {
  const template = getDefaultAnchorTemplate();
  document.querySelectorAll("a.equation-anchor").forEach(function (anchor) {
    alignEquationAnchorWithDefault(anchor, template);
  });
}

function ensureEquationAnchorStyles() {
  if (document.getElementById("equation-anchor-styles")) {
    return;
  }

  const style = document.createElement("style");
  style.id = "equation-anchor-styles";
  style.textContent = `
    .equation-anchor-target {
      --equation-anchor-offset: 1.2rem;
      position: relative;
      display: block;
    }
    .equation-anchor {
      position: absolute;
      left: calc(-1 * var(--equation-anchor-offset));
      top: 50%;
      transform: translateY(-50%);
      text-decoration: none;
      opacity: 0.7;
      font-size: 0.9em;
    }
    .equation-anchor:hover {
      opacity: 1;
    }
    .equation-anchor-icon {
      width: 0.9em;
      height: 0.9em;
      vertical-align: -0.125em;
    }
  `;
  document.head.appendChild(style);
}

document.addEventListener("DOMContentLoaded", function () {
  ensureEquationAnchorStyles();

  let counter = 0;

  document.querySelectorAll(".math.display").forEach(function (mathEl) {
    // For labeled equations, Quarto wraps the math display span in an eq-* span.
    // For unlabeled equations, use the parent element (typically a <p>).
    const labeledContainer = mathEl.closest("[id^='eq-']");
    const target = labeledContainer || mathEl.parentElement;

    if (!target) {
      return;
    }

    // Skip if already processed.
    if (target.querySelector(".equation-anchor")) {
      return;
    }

    // Use the labeled container's id, or assign an auto-generated id.
    let id = labeledContainer ? labeledContainer.id : target.id;
    if (!id) {
      counter++;
      id = "eq-anchor-" + counter;
      target.id = id;
    }

    target.classList.add("equation-anchor-target");

    const anchor = document.createElement("a");
    anchor.className = "equation-anchor anchorjs-link";
    anchor.href = "#" + id;
    anchor.setAttribute("aria-label", "Permalink to this equation");
    target.appendChild(anchor);
  });

  alignEquationAnchorsWithDefault();
});

window.addEventListener("load", alignEquationAnchorsWithDefault);
</script>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/ucdavis\.github\.io\/win\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>